---
- name: "Extract artifact to EC2"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu

- name: "Start application"
  shell: |
    npm install -f
    pm2 start npm -- start -f
  