---
- name: npm Install
  become: true
  raw: npm install

- name: "pm2 stop default"
  become: true
  raw: pm stop default

- name: "pm2 start npm -- start."
  become: true
  raw: sudo pm2 start npm -- start
  
